"""Per-plot CSV exports for the Climate Dashboard.

Every figure panel on the dashboard carries a "Download CSV" link pointing
at a file under ``assets/data/`` that contains exactly the data plotted,
regenerated by the daily update pipeline (``run.py update``). Filenames are
stable so links never break; each file starts with ``#`` comment lines
documenting the source, baseline, and units (always °C). Read with
``pandas.read_csv(path, comment='#')``.

Toggle states that change the plotted data map to separate files (e.g.
``enso_plume_oni.csv`` / ``enso_plume_roni.csv``); toggles that only
restyle the figure (dark mode, °C/°F display, static/interactive) do not.
"""

import logging
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

CSV_DIR = Path(__file__).resolve().parent.parent / "assets" / "data"

_REPO = "https://github.com/hausfath/climate-dashboard"

# Kept in sync with the highlighted years in the daily context plots
_ENSO_INDEX_MODES = ("oni", "roni")


def _write(df: pd.DataFrame, filename: str, title: str, notes=(),
           float_format: str = "%.4f", index: bool = False) -> None:
    """Write ``df`` to assets/data/<filename> with a commented header.

    If nothing but the generation-date stamp changed, the existing file is
    left untouched so unchanged datasets don't churn in git every day.
    """
    CSV_DIR.mkdir(parents=True, exist_ok=True)
    path = CSV_DIR / filename
    stamp_line = (f"# Climate Dashboard ({_REPO}) — regenerated daily; "
                  f"this file: {date.today().isoformat()}")
    lines = [f"# {title}", stamp_line]
    lines += [f"# {n}" for n in notes]
    lines.append("# All values in degrees Celsius unless a column "
                 "says otherwise. Load with pandas.read_csv(..., comment='#').")
    content = "\n".join(lines) + "\n" + df.to_csv(
        index=index, float_format=float_format)

    if path.exists():
        old = path.read_text()
        strip = lambda s: "\n".join(
            l for l in s.splitlines() if not l.startswith("# Climate Dashboard"))
        if strip(old) == strip(content):
            logger.info(f"{path.name} unchanged; kept existing file")
            return
    path.write_text(content)
    logger.info(f"Wrote {path.name} ({len(df)} rows)")


# ---------------------------------------------------------------------------
# Global Temperature tab
# ---------------------------------------------------------------------------

def export_timeseries(df: pd.DataFrame) -> None:
    """Main timeseries panel: daily + annual files, each with observed and
    ENSO-removed columns (covers all four toggle states with two files)."""
    from src.dashboard import adjust_anomalies_to_preindustrial
    from src.enso_removal import remove_enso

    adj = adjust_anomalies_to_preindustrial(df).sort_values("date")
    rm = remove_enso(adj)

    daily = pd.DataFrame({
        "date": adj["date"].dt.strftime("%Y-%m-%d"),
        "anomaly_c": adj["anomaly"].values,
        "anomaly_enso_removed_c": rm["anomaly"].values,
        "rolling_365d_c": adj["anomaly"].rolling(365, center=True).mean().values,
        "rolling_365d_enso_removed_c":
            rm["anomaly"].rolling(365, center=True).mean().values,
    })
    _write(daily, "timeseries_daily.csv",
           "Daily global mean surface temperature anomaly (ERA5, 1940-present)",
           ["Anomalies vs preindustrial 1850-1900 (ERA5 1991-2020 climatology "
            "plus monthly preindustrial offsets).",
            "ENSO-removed columns subtract the lagged-ONI ENSO component "
            "(~0.1 degC per unit ONI at ~3-month lag); trend untouched.",
            "rolling_365d columns are 365-day centered means.",
            "Source: ECMWF ERA5 via Copernicus Climate Pulse."])

    cur_year = int(adj["date"].dt.year.max())
    g = adj.groupby(adj["date"].dt.year)["anomaly"].agg(["mean", "size"])
    g_rm = rm.groupby(rm["date"].dt.year)["anomaly"].mean()
    annual = pd.DataFrame({
        "year": g.index.astype(int),
        "annual_mean_c": g["mean"].values,
        "annual_mean_enso_removed_c": g_rm.reindex(g.index).values,
        "n_days": g["size"].astype(int).values,
    })
    annual["status"] = np.where(annual["year"] == cur_year, "year_to_date",
                                np.where(annual["n_days"] >= 360,
                                         "complete", "partial"))
    _write(annual, "timeseries_annual.csv",
           "Annual global mean surface temperature anomaly (ERA5)",
           ["Calendar-year means of the daily anomalies vs preindustrial "
            "1850-1900; the current year is a year-to-date mean.",
            "ENSO-removed column as in timeseries_daily.csv.",
            "Source: ECMWF ERA5 via Copernicus Climate Pulse."])


def export_year_context(df: pd.DataFrame) -> None:
    """'The year in context' panel: era envelopes + highlighted years
    (+ the EC46 forecast tail on the anomaly variant)."""
    from src.dashboard import (ERA_BANDS, THEME_CONFIG, _ec46_anomalize,
                               _load_ec46_forecast,
                               adjust_anomalies_to_preindustrial)

    years_hl = sorted(THEME_CONFIG["light"]["highlight_colors"])
    adj = adjust_anomalies_to_preindustrial(df)

    for mode, data, col in (("anomaly", adj, "anomaly"),
                            ("absolute", df, "temperature")):
        out = pd.DataFrame(index=pd.RangeIndex(1, 367, name="day_of_year"))
        for start, end in ERA_BANDS:
            era = data[(data["year"] >= start) & (data["year"] <= end)]
            grouped = era.groupby("day_of_year")[col]
            out[f"era_{start}_{end}_p05"] = (grouped.quantile(0.05)
                .rolling(7, center=True, min_periods=1).mean())
            out[f"era_{start}_{end}_p95"] = (grouped.quantile(0.95)
                .rolling(7, center=True, min_periods=1).mean())
        for year in years_hl:
            yd = data[data["year"] == year]
            out[str(year)] = yd.set_index("day_of_year")[col]

        notes = [
            "Rows are day-of-year; era columns are the 5th/95th percentile "
            "envelope per era (7-day smoothed); year columns are the "
            "highlighted recent years.",
            ("Anomalies vs preindustrial 1850-1900." if mode == "anomaly"
             else "Absolute global mean 2m temperature."),
            "Source: ECMWF ERA5 via Copernicus Climate Pulse."]

        if mode == "anomaly":
            try:
                ec46 = _load_ec46_forecast()
                fc = _ec46_anomalize(ec46, adj) if ec46 is not None else None
            except Exception:
                fc = None
            if fc is not None and not fc.empty:
                fc = fc.copy()
                fc["day_of_year"] = fc["date"].dt.dayofyear
                fc = fc.set_index("day_of_year")
                for src_col, dst in (("t2m_mean", "ec46_mean"),
                                     ("t2m_p5", "ec46_p05"),
                                     ("t2m_p25", "ec46_p25"),
                                     ("t2m_p75", "ec46_p75"),
                                     ("t2m_p95", "ec46_p95")):
                    out[dst] = fc[src_col]
                notes.insert(2, "ec46_* columns: ECMWF EC46 46-day forecast "
                             "(ensemble mean and percentiles), bias-corrected "
                             "and expressed as the same preindustrial anomaly.")
        _write(out.reset_index(), f"year_context_{mode}.csv",
               f"Recent years vs the historical range — daily "
               f"{'anomalies' if mode == 'anomaly' else 'absolute temperatures'}"
               " by day of year (ERA5)", notes)


def export_monthly_projection(df: pd.DataFrame) -> None:
    """Monthly projection panel: historical means for the current month plus
    the month-to-date value and the projection (EC46 blend, or the
    regression fallback — the method is recorded in the file)."""
    from src.dashboard import (adjust_anomalies_to_preindustrial,
                               get_monthly_projection)

    adj = adjust_anomalies_to_preindustrial(df)
    latest = adj["date"].max()
    month, year = latest.month, latest.year
    month_name = latest.strftime("%B")

    proj = get_monthly_projection(adj)
    pred = proj.get("prediction")
    mtd = proj.get("mtd_avg")

    md = adj[adj["date"].dt.month == month]
    monthly = md.groupby(md["date"].dt.year)["anomaly"].mean()

    out = pd.DataFrame({"year": monthly.index.astype(int),
                        "monthly_mean_c": monthly.values})
    out.loc[out["year"] == year, "monthly_mean_c"] = np.nan
    cur = out["year"] == year
    out["month_to_date_c"] = np.where(cur, mtd, np.nan)
    out["projected_c"] = np.where(cur, pred, np.nan)
    for k, col in (("lo95", "projection_p05_c"), ("lo50", "projection_p25_c"),
                   ("hi50", "projection_p75_c"), ("hi95", "projection_p95_c")):
        out[col] = np.where(cur, proj.get(k, np.nan), np.nan)
    out["method"] = np.where(cur, proj.get("method", ""), "")

    if proj.get("method") == "ec46_blend":
        method_note = (
            f"Projection: median and calibrated quantiles of the ECMWF EC46 "
            f"46-day ensemble ({proj.get('n_members', '?')} members, init "
            f"{proj.get('init_date', '?')}) blended with "
            f"{proj.get('days_in', '?')} days of month-to-date observations; "
            "interval widths include verified model-error terms and are "
            "capped against overconfidence while the verification archive "
            "is short.")
    else:
        method_note = (
            f"Projection: regression of full-{month_name} means on "
            "month-to-date means across all prior years (EC46 blend "
            "unavailable for this file); the p05/p95 columns are +/-2 sigma "
            "of the regression residuals.")
    _write(out, "monthly_projection.csv",
           f"{month_name} global mean anomaly by year, with the "
           f"{month_name} {year} projection (ERA5)",
           ["Anomalies vs preindustrial 1850-1900.", method_note,
            "The current year's monthly_mean_c is left blank (incomplete "
            "month); its month-to-date and projection ride in their own "
            "columns."])


def export_annual_prediction(df: pd.DataFrame, enso_df=None) -> None:
    """Annual anomaly & prediction panel. The regression + Monte Carlo lives
    inside the plot function, so extract the plotted traces — this guarantees
    the CSV matches the figure."""
    from src.dashboard import create_annual_prediction_plot

    fig = create_annual_prediction_plot(df, enso_df, dark_mode=False)
    obs = next((t for t in fig.data if (t.name or "") == "Observed"), None)
    ytd = next((t for t in fig.data if "YTD" in (t.name or "")), None)
    proj = next((t for t in fig.data if "projection" in (t.name or "")), None)
    if obs is None or len(obs.x) < 30:
        raise RuntimeError("annual prediction figure missing Observed trace")

    out = pd.DataFrame({"year": np.asarray(obs.x, dtype=int),
                        "annual_mean_c": np.asarray(obs.y, dtype=float)})
    extra = {}
    if ytd is not None:
        extra["year"] = int(ytd.x[0])
        extra["ytd_mean_c"] = float(ytd.y[0])
    if proj is not None:
        extra["year"] = int(proj.x[0])
        extra["projected_c"] = float(proj.y[0])
        up = float(np.asarray(proj.error_y["array"])[0])
        down = float(np.asarray(proj.error_y["arrayminus"])[0])
        extra["projection_lo_c"] = extra["projected_c"] - down
        extra["projection_hi_c"] = extra["projected_c"] + up
    if extra:
        out = pd.concat([out, pd.DataFrame([extra])], ignore_index=True)
    _write(out, "annual_prediction.csv",
           "Annual global mean anomaly and current-year prediction (ERA5)",
           ["Anomalies vs preindustrial 1850-1900; complete calendar years "
            "plus the current year's year-to-date mean and projection.",
            "Projection: regression on year, prior-year anomaly, observed/"
            "forecast ENSO, trailing-30-day and year-to-date anomalies; the "
            "lo/hi interval is a 95% Monte Carlo range over the ENSO "
            "multi-model ensemble plus regression residuals."])


def export_rank_probabilities(stats: dict) -> None:
    """Ranking-probabilities table (uses the already-computed stats dict)."""
    probs = stats.get("annual_rank_probs") or []
    if not probs:
        logger.warning("No annual rank probabilities to export")
        return
    out = pd.DataFrame(probs)[["rank", "rank_label", "prob",
                               "holder_year", "holder_value"]]
    out = out.rename(columns={"prob": "probability",
                              "holder_value": "holder_value_c"})
    _write(out, "rank_probabilities.csv",
           f"Where {stats.get('current_year', '')} likely ranks — final-rank "
           "probabilities from the Monte Carlo ensemble",
           ["probability is the fraction of Monte Carlo draws (ENSO "
            "multi-model ensemble plus regression residuals) landing at "
            "each final rank; rank 1 = warmest on record.",
            "holder_year / holder_value_c: the year currently holding that "
            "rank and its annual anomaly (degC vs preindustrial 1850-1900)."],
           float_format="%.4f")


def export_projection_history(df: pd.DataFrame) -> None:
    """How the projection has evolved: pass through the history file."""
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from config import DATA_DIR

    year = int(df["year"].max())
    path = DATA_DIR / f"projection_history_{year}.csv"
    if not path.exists():
        logger.warning(f"{path.name} not found; skipping export")
        return
    h = pd.read_csv(path)
    out = pd.DataFrame({
        "date": h["date"],
        "projected_annual_c": h["prediction"],
        "sigma_c": h["uncertainty"],
        "ci95_lo_c": h["prediction"] - 2 * h["uncertainty"],
        "ci95_hi_c": h["prediction"] + 2 * h["uncertainty"],
        "ytd_mean_c": h["ytd_anomaly"],
    })
    _write(out, "projection_history.csv",
           f"How the {year} annual projection has evolved (daily)",
           ["Each row is the projection issued on that date, from data "
            "available through that date; anomalies vs preindustrial "
            "1850-1900.",
            "ci95 columns are the projection +/- 2 sigma."])


def export_heatmaps(df: pd.DataFrame) -> None:
    """'Every day since 1940' heatmaps: day-of-year x year matrices."""
    from src.dashboard import adjust_anomalies_to_preindustrial

    adj = adjust_anomalies_to_preindustrial(df)
    for mode, data, col, note in (
            ("anomaly", adj, "anomaly",
             "Anomalies vs preindustrial 1850-1900."),
            ("absolute", df, "temperature",
             "Absolute global mean 2m temperature.")):
        wide = data.pivot(index="day_of_year", columns="year", values=col)
        wide.columns = wide.columns.astype(int)
        _write(wide.reset_index(), f"heatmap_{mode}.csv",
               f"Every day since 1940 — daily global mean "
               f"{'anomaly' if mode == 'anomaly' else 'temperature'} "
               "matrix (ERA5)",
               ["Rows are day-of-year (1-366), columns are years — the "
                "heatmap grid exactly.", note,
                "Source: ECMWF ERA5 via Copernicus Climate Pulse."],
               float_format="%.3f")


# ---------------------------------------------------------------------------
# ENSO tab
# ---------------------------------------------------------------------------

_NINO_REGION_TITLES = {"nino12": "Nino 1+2", "nino3": "Nino 3",
                       "nino34": "Nino 3.4", "nino4": "Nino 4"}


def export_nino_daily_years() -> None:
    """Daily year-lines figure: one long-format file per region (ONI
    convention) plus the RONI variant (Niño 3.4 only, by definition).

    Deliberately imports only src.nino_daily (no plotting stack) so the
    lightweight afternoon OISST cron can refresh these files too."""
    from src.nino_daily import (era_relative_anomalies as
                                _era_relative_anomalies,
                                load_nino34_history)

    hist = load_nino34_history()
    base_notes = [
        "Anomalies vs centered 30-year day-of-year climatologies (the ONI "
        "convention: each year measured against its own era, windows "
        "clamped at the record edges, current year excluded), so the "
        "warming trend is removed and years compare as ENSO states.",
        "Feb 29 values are mapped to day-of-year 59 (Feb 28) so years align.",
        "Source: NOAA OISST v2.1 daily box means."]

    for region in ("nino34", "nino12", "nino3", "nino4"):
        d = _era_relative_anomalies(hist, "oni", region=region)
        if d is None or d.empty:
            logger.warning(f"No daily data for region {region}; skipping")
            continue
        out = d[["date", "year", "doy", "anom"]].rename(
            columns={"doy": "day_of_year", "anom": "anomaly_c"})
        out["date"] = pd.to_datetime(out["date"]).dt.strftime("%Y-%m-%d")
        _write(out, f"nino_daily_years_{region}.csv",
               f"This year vs every year since 1982 — daily "
               f"{_NINO_REGION_TITLES[region]} SST anomaly", base_notes,
               float_format="%.3f")

    d = _era_relative_anomalies(hist, "roni")
    if d is not None and not d.empty:
        out = d[["date", "year", "doy", "anom"]].rename(
            columns={"doy": "day_of_year", "anom": "anomaly_c"})
        out["date"] = pd.to_datetime(out["date"]).dt.strftime("%Y-%m-%d")
        _write(out, "nino_daily_years_roni.csv",
               "This year vs every year since 1982 — daily RONI "
               "(relative Nino 3.4)",
               ["RONI: Nino 3.4 anomaly minus the tropical-mean (20S-20N) "
                "SST anomaly, scaled by L'Heureux et al. monthly factors."]
               + base_notes, float_format="%.3f")

    # Absolute-SST variants (the figure's Anomaly/Absolute toggle)
    from src.nino_daily import FIRST_NINO_YEAR, _doy_key
    for region in ("nino34", "nino12", "nino3", "nino4"):
        if region not in hist.columns:
            continue
        d = hist.copy()
        d["year"] = d["date"].dt.year
        d["day_of_year"] = _doy_key(pd.DatetimeIndex(d["date"]))
        d = d[d["year"] >= FIRST_NINO_YEAR].dropna(subset=[region])
        out = d[["date", "year", "day_of_year", region]].rename(
            columns={region: "sst_c"})
        out["date"] = pd.to_datetime(out["date"]).dt.strftime("%Y-%m-%d")
        _write(out, f"nino_daily_years_{region}_abs.csv",
               f"This year vs every year since 1982 — daily "
               f"{_NINO_REGION_TITLES[region]} absolute SST",
               ["Raw daily box-mean SST (degC), seasonal cycle retained.",
                "Feb 29 values are mapped to day-of-year 59 (Feb 28) so "
                "years align.",
                "Source: NOAA OISST v2.1 daily box means."],
               float_format="%.3f")


def _prep_mega(forecast_df, index_mode):
    """Shared prep: swap the index column in and build the deduplicated
    member/mean frames, filtered to months with >=4 models (as plotted)."""
    from src.enso_plots import (_build_mega_df, _get_forecast_only,
                                _index_meta, _swap_to_nino34)
    meta = _index_meta(index_mode)
    fdf = _swap_to_nino34(forecast_df, meta["col"])
    mega = _build_mega_df(_get_forecast_only(fdf))
    members = mega[mega["member_id"] != "mean"].copy()
    means = mega[mega["member_id"] == "mean"].copy()
    models_per_month = means.groupby("target_month")["model"].nunique()
    valid = models_per_month[models_per_month >= 4].index
    return (members[members["target_month"].isin(valid)].copy(),
            means[means["target_month"].isin(valid)].copy(), meta)


def _idx_label(index_mode):
    return "RONI (relative Nino 3.4)" if index_mode == "roni" else \
        "ONI (Nino 3.4)"


def export_enso_plume(forecast_df, obs_df, index_mode="oni") -> None:
    """Combined forecast plume: weighted percentile fan, per-model ensemble
    means, multi-model median, and recent observed values."""
    from src.enso_plots import (_multimodel_weighted_median, _swap_to_nino34,
                                _target_month_to_date, _weighted_quantile)

    members, means, meta = _prep_mega(forecast_df, index_mode)
    if members.empty:
        logger.warning(f"No plume members for {index_mode}; skipping")
        return

    rows = []
    for tm in sorted(members["target_month"].unique()):
        tm_m = members[members["target_month"] == tm]
        counts = tm_m.groupby("model").size()
        w = tm_m["model"].map(lambda m: 1.0 / counts[m]).values
        v = tm_m["nino34_anom"].values
        mask = ~np.isnan(v)
        if mask.sum() == 0:
            continue
        rows.append({"target_month": tm,
                     **{f"p{int(q * 100):02d}":
                        _weighted_quantile(v[mask], w[mask], q)
                        for q in (0.05, 0.25, 0.75, 0.95)}})
    fan = pd.DataFrame(rows).set_index("target_month")

    mm = _multimodel_weighted_median(members).set_index("target_month")
    fan["multimodel_median_c"] = mm["nino34_anom"]

    model_means = means.pivot_table(index="target_month", columns="model",
                                    values="nino34_anom", aggfunc="first")
    model_means.columns = [f"mean_{m}" for m in model_means.columns]
    out = fan.join(model_means)

    if obs_df is not None and not obs_df.empty:
        odf = _swap_to_nino34(obs_df, meta["col"]).copy()
        odf["target_month"] = (pd.to_datetime(odf["date"])
                               .dt.to_period("M").astype(str))
        obs_series = odf.set_index("target_month")["nino34_anom"]
        obs_series = obs_series[~obs_series.index.duplicated(keep="last")]
        out = out.join(obs_series.rename("observed_c"), how="outer")
        out = out[out.index >= "2025-12"]

    out = out.sort_index().reset_index()
    label = _idx_label(index_mode)
    _write(out, f"enso_plume_{index_mode}.csv",
           f"Combined ENSO forecast plume — {label}",
           ["p05/p25/p75/p95: model-weighted percentiles across all "
            "ensemble members (each model weighted equally regardless of "
            "ensemble size); months with fewer than 4 models are dropped.",
            "mean_<model>: that model's ensemble-mean forecast; "
            "multimodel_median_c: the model-weighted median (forecast only, "
            "no observed substitution); observed_c: observed monthly index.",
            "Member-level values are in enso_members_" + index_mode + ".csv."])


def export_enso_members(forecast_df, index_mode="oni") -> None:
    """Monthly forecast distribution: every ensemble member value."""
    members, _, _ = _prep_mega(forecast_df, index_mode)
    if members.empty:
        logger.warning(f"No members for {index_mode}; skipping")
        return
    cols = ["target_month", "model", "member_id", "nino34_anom"]
    if "init_date" in members.columns:
        cols.insert(3, "init_date")
    out = (members[cols]
           .rename(columns={"nino34_anom": "anomaly_c"})
           .sort_values(["target_month", "model", "member_id"]))
    label = _idx_label(index_mode)
    _write(out, f"enso_members_{index_mode}.csv",
           f"ENSO forecast ensemble members — {label}",
           ["One row per ensemble member per target month (deduplicated "
            "multi-model plume; months with fewer than 4 models dropped).",
            "Dashboard statistics weight each model equally regardless of "
            "ensemble size. CFSv2 member ens_E3_041 is the control run and "
            "is excluded from the dashboard's probability statistics."])


def export_enso_strength_probs(forecast_df, index_mode="oni") -> None:
    """Strength probabilities by season."""
    from src.enso_plots import (STRENGTH_BINS, _season_label,
                                compute_strength_probabilities)

    centers, probs, n_models = compute_strength_probabilities(
        forecast_df, index_mode=index_mode)
    if not len(centers):
        logger.warning(f"No strength probabilities for {index_mode}")
        return
    colnames = [b[0].lower().replace(" ", "_")
                .replace("ñ", "n") + "_pct" for b in STRENGTH_BINS]
    out = pd.DataFrame(probs, columns=colnames)
    out.insert(0, "season", [_season_label(c) for c in centers])
    out.insert(1, "season_center", [c.strftime("%Y-%m") for c in centers])
    out["n_models"] = n_models
    label = _idx_label(index_mode)
    _write(out, f"enso_strength_probs_{index_mode}.csv",
           f"ENSO strength probabilities by season — {label}",
           ["Model-weighted category probabilities (percent) per "
            "overlapping 3-month season, from the multi-model ensemble; "
            "observed months are blended into seasonal means where "
            "available.",
            "Categories use ONI event thresholds (0.5/1.0/1.5/2.0 degC).",
            "n_models: number of forecast systems contributing to that "
            "season."], float_format="%.2f")


def export_enso_historical(index_mode="oni") -> None:
    """Historical record + current forecast panel (observed monthly series
    back to 1990, multi-model weighted median forecast with 25-75% band)."""
    from src.enso_plots import (_build_mega_df, _get_forecast_only,
                                _index_meta, _multimodel_weighted_median,
                                _swap_to_nino34, _target_month_to_date,
                                _weighted_quantile, load_enso_forecast_data,
                                load_full_observed)
    from src.enso_skill import _load_observed_oisst

    meta = _index_meta(index_mode)
    forecast_df, _, _ = load_enso_forecast_data()

    obs_full = load_full_observed(start_year=1990)
    obs_full = _swap_to_nino34(obs_full, meta["col"])
    fdf = _swap_to_nino34(forecast_df, meta["col"])
    obs_full = obs_full.dropna(subset=["nino34_anom"]).reset_index(drop=True)

    # Overlay OISSTv2.1 monthly means (complete months only), as the chart's
    # observed truth does.
    try:
        oisst = _load_observed_oisst(index_mode, start="1990-01-01")
    except Exception:
        oisst = pd.DataFrame()
    if not oisst.empty:
        oisst_map = oisst.set_index("date")["value"]
        obs_full = obs_full.set_index("date")
        overlap = obs_full.index.intersection(oisst_map.index)
        obs_full.loc[overlap, "nino34_anom"] = oisst_map[overlap]
        new_months = oisst_map.index.difference(obs_full.index)
        if len(new_months):
            add = pd.DataFrame({"date": new_months,
                                "nino34_anom": oisst_map[new_months].values})
            obs_full = pd.concat([obs_full.reset_index(), add],
                                 ignore_index=True).set_index("date")
        obs_full = obs_full.sort_index().reset_index()

    obs_lookup = obs_full.set_index(
        obs_full["date"].dt.to_period("M").astype(str))["nino34_anom"]

    forecast_only = _get_forecast_only(fdf)
    mega = _build_mega_df(forecast_only)
    means = mega[mega["member_id"] == "mean"].copy()
    fc_members = mega[mega["member_id"] != "mean"].copy()
    models_per_month = means.groupby("target_month")["model"].nunique()
    valid_months = models_per_month[models_per_month >= 4].index
    fc_members = fc_members[fc_members["target_month"].isin(valid_months)]

    mm = _multimodel_weighted_median(fc_members)
    mm["date"] = mm["target_month"].apply(_target_month_to_date)
    for idx, row in mm.iterrows():
        if row["target_month"] in obs_lookup.index:
            mm.loc[idx, "nino34_anom"] = obs_lookup[row["target_month"]]

    q25_map, q75_map = {}, {}
    for tm in sorted(mm["target_month"].unique()):
        if tm in obs_lookup.index:
            q25_map[tm] = q75_map[tm] = float(obs_lookup[tm])
            continue
        tm_members = fc_members[fc_members["target_month"] == tm]
        vals = tm_members["nino34_anom"].values
        valid = ~np.isnan(vals)
        if tm_members.empty or valid.sum() == 0:
            q25_map[tm] = q75_map[tm] = np.nan
            continue
        counts = tm_members.groupby("model").size()
        w = tm_members["model"].map(lambda m: 1.0 / counts[m]).values
        q25_map[tm] = _weighted_quantile(vals[valid], w[valid], 0.25)
        q75_map[tm] = _weighted_quantile(vals[valid], w[valid], 0.75)

    fc_rows = []
    for _, row in mm.sort_values("date").iterrows():
        tm = row["target_month"]
        fc_rows.append({
            "date": row["date"].strftime("%Y-%m-%d"),
            "is_forecast": tm not in obs_lookup.index,
            "observed_c": (float(obs_lookup[tm])
                           if tm in obs_lookup.index else np.nan),
            "forecast_median_c": float(row["nino34_anom"]),
            "forecast_q25_c": q25_map.get(tm, np.nan),
            "forecast_q75_c": q75_map.get(tm, np.nan),
            "n_models": int(models_per_month.get(tm, 0)),
        })
    fc_df = pd.DataFrame(fc_rows)

    fc_months = set(pd.to_datetime(fc_df["date"]).dt.strftime("%Y-%m"))
    pre_rows = []
    for _, row in obs_full.iterrows():
        if row["date"].strftime("%Y-%m") in fc_months:
            continue
        pre_rows.append({"date": row["date"].strftime("%Y-%m-%d"),
                         "is_forecast": False,
                         "observed_c": float(row["nino34_anom"]),
                         "forecast_median_c": np.nan,
                         "forecast_q25_c": np.nan,
                         "forecast_q75_c": np.nan,
                         "n_models": 0})
    full = (pd.concat([pd.DataFrame(pre_rows), fc_df], ignore_index=True)
            .sort_values("date").reset_index(drop=True))

    label = _idx_label(index_mode)
    _write(full, f"enso_historical_{index_mode}.csv",
           f"Historical ENSO record and current forecast — {label}",
           ["Observed monthly index back to 1990 (NOAA, with OISSTv2.1 "
            "monthly means overlaid for recent months), plus the "
            "multi-model weighted-median forecast with its 25th-75th "
            "percentile band (months with fewer than 4 models dropped).",
            "Forecast months that already verify are shown as observed "
            "(is_forecast=False)."])


# ---------------------------------------------------------------------------
# Models vs Obs tab
# ---------------------------------------------------------------------------

_MODEL_BASELINES = ("1850-1900", "1951-1980", "1961-1990",
                    "1971-2000", "1981-2010")
_OBS_COLS = ["hadcrut5", "gistemp", "noaa", "berkeley", "copernicus"]
_OBS_TITLES = {"hadcrut5": "HadCRUT5", "gistemp": "GISTEMP", "noaa": "NOAA",
               "berkeley": "Berkeley Earth", "copernicus": "ERA5 (C3S)"}


def baseline_slug(baseline: str) -> str:
    return baseline.replace("-", "_")


def export_models_timeseries(cmip_df, obs_df, gen: str,
                             baseline: str) -> None:
    """Models-vs-obs scorecard: monthly ensemble stats + the five
    observational records on the selected baseline."""
    from src.models_vs_obs import compute_ensemble_stats, scenario_for

    bl_start, bl_end = (int(x) for x in baseline.split("-"))
    stats = compute_ensemble_stats(cmip_df, baseline_start=bl_start,
                                   baseline_end=bl_end)
    stats = stats[(stats["date"].dt.year >= 1900) &
                  (stats["date"].dt.year <= 2040)]

    obs = obs_df.copy()
    if baseline != "1850-1900":
        m = ((obs["date"].dt.year >= bl_start) &
             (obs["date"].dt.year <= bl_end))
        for c in _OBS_COLS:
            if c in obs.columns:
                bl_mean = obs.loc[m, c].mean()
                if not np.isnan(bl_mean):
                    obs[c] = obs[c] - bl_mean

    out = stats[["date", "mean", "p05", "p95"]].rename(
        columns={"mean": "model_mean_c", "p05": "model_p05_c",
                 "p95": "model_p95_c"})
    obs_cols = [c for c in _OBS_COLS if c in obs.columns]
    out = out.merge(obs[["date"] + obs_cols], on="date", how="left")
    out["obs_median_c"] = out[obs_cols].median(axis=1)
    out["date"] = out["date"].dt.strftime("%Y-%m-%d")

    gen_label = gen.upper()
    _write(out, f"models_timeseries_{gen}_{baseline_slug(baseline)}.csv",
           f"Climate models vs observations — {gen_label} "
           f"({scenario_for(gen)}), baseline {baseline}",
           [f"Monthly means, all series referenced to {baseline}. "
            "model_mean/p05/p95: ensemble mean and 5th-95th percentile "
            "across members.",
            "Observation columns: " + ", ".join(
                _OBS_TITLES[c] for c in obs_cols) + ".",
            "The dashboard's 12-month view is a 12-month rolling mean of "
            "these monthly columns."], float_format="%.4f")


def export_models_trends(cmip_df, obs_df, gen: str) -> None:
    """Warming trend by start year."""
    from src.models_vs_obs import (compute_variable_start_trends,
                                   scenario_for)

    data = compute_variable_start_trends(cmip_df, obs_df)
    out = pd.DataFrame({"start_year": data["start_years"],
                        "model_mean": data["model_mean"],
                        "model_p05": data["model_p05"],
                        "model_p95": data["model_p95"]})
    for c in _OBS_COLS:
        if f"obs_{c}" in data:
            out[c] = data[f"obs_{c}"]
    obs_cols = [c for c in _OBS_COLS if c in out.columns]
    out["obs_median"] = out[obs_cols].median(axis=1)

    gen_label = gen.upper()
    _write(out, f"models_trends_{gen}.csv",
           f"Warming trend by start year (to present) — {gen_label} "
           f"({scenario_for(gen)})",
           ["OLS trends in degC per decade from each start year through the "
            "latest observed month; model columns are the ensemble mean and "
            "5th-95th percentile across members.",
            "Trends are baseline-independent."], float_format="%.4f")


def export_models_trend_members(cmip_df, obs_df, gen: str) -> None:
    """Trend histograms: per-member trends for the three fixed windows."""
    from src.models_vs_obs import (_trend_cdecade, calculate_obs_trends,
                                   scenario_for)

    last_obs = obs_df["date"].max()
    end = last_obs.strftime("%Y-%m-%d")
    periods = [("1970-01-01", "1970-present"),
               ("2001-01-01", "2001-present"),
               ("2011-01-01", "2011-present")]
    ens_cols = [c for c in cmip_df.columns if c.startswith("ens_")]

    rows = []
    for start, label in periods:
        sub = cmip_df[(cmip_df["date"] >= start) & (cmip_df["date"] <= end)]
        for col in ens_cols:
            s = sub[col].dropna()
            if len(s) < 12:
                continue
            rows.append({"period": label, "source": "model_member",
                         "name": col.replace("ens_", "", 1),
                         "trend_c_per_decade":
                             _trend_cdecade(sub.loc[s.index, "date"], s)})
        for c, v in calculate_obs_trends(obs_df, start, end).items():
            if v is not None:
                rows.append({"period": label, "source": "observed",
                             "name": _OBS_TITLES.get(c, c),
                             "trend_c_per_decade": v})

    gen_label = gen.upper()
    _write(pd.DataFrame(rows), f"models_trend_members_{gen}.csv",
           f"Per-member warming trends for three windows — {gen_label} "
           f"({scenario_for(gen)})",
           ["OLS trends in degC per decade through the latest observed "
            "month; source distinguishes individual model ensemble members "
            "from the five observational records.",
            "These are the values binned in the dashboard's trend "
            "histograms."], float_format="%.4f")


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def generate_all_csv_exports(df: pd.DataFrame, enso_df=None,
                             stats: dict | None = None) -> None:
    """Regenerate every downloadable CSV. Each step fails independently so
    one bad source never blocks the rest (mirrors the static-image flow)."""

    def _step(fn, *args, **kwargs):
        try:
            fn(*args, **kwargs)
        except Exception as e:
            logger.error(f"CSV export {fn.__name__} failed: {e}")

    _step(export_timeseries, df)
    _step(export_year_context, df)
    _step(export_monthly_projection, df)
    _step(export_annual_prediction, df, enso_df)
    _step(export_projection_history, df)
    _step(export_heatmaps, df)

    if stats is None:
        try:
            from src.dashboard import create_statistics_cards
            stats = create_statistics_cards(df)
        except Exception as e:
            logger.error(f"Stats for rank probabilities failed: {e}")
            stats = None
    if stats:
        _step(export_rank_probabilities, stats)

    _step(export_nino_daily_years)

    try:
        from src.enso_plots import load_enso_forecast_data
        ef, eo, _ = load_enso_forecast_data()
        if not ef.empty:
            for idx in _ENSO_INDEX_MODES:
                _step(export_enso_plume, ef, eo, idx)
                _step(export_enso_members, ef, idx)
                _step(export_enso_strength_probs, ef, idx)
                _step(export_enso_historical, idx)
    except Exception as e:
        logger.error(f"ENSO CSV exports failed: {e}")

    try:
        from src.models_vs_obs import load_cmip_ensemble, load_obs_data
        obs = load_obs_data()
        for gen in ("cmip3", "cmip5", "cmip6"):
            cmip = load_cmip_ensemble(gen)
            if cmip.empty:
                continue
            for baseline in _MODEL_BASELINES:
                _step(export_models_timeseries, cmip, obs, gen, baseline)
            _step(export_models_trends, cmip, obs, gen)
            _step(export_models_trend_members, cmip, obs, gen)
    except Exception as e:
        logger.error(f"Models CSV exports failed: {e}")

    logger.info("All CSV exports complete")


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    logging.basicConfig(level=logging.INFO)

    if "--nino-daily" in sys.argv:
        # Lightweight mode for the afternoon OISST top-up cron: refresh
        # only the daily Niño year-lines CSVs (pandas/numpy only).
        export_nino_daily_years()
    else:
        from config import DATA_SOURCES
        from src.scraper import load_or_fetch_data

        source = DATA_SOURCES["era5_global"]
        _df = load_or_fetch_data(source["url"], source["local_file"])
        generate_all_csv_exports(_df)
